// <auto-generated />
using System;
using EventManager.API.Domain.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventManager.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918120814_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventManager.API.Models.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("EventManager.API.Models.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 3,
                            Description = "Annual gathering of tech leaders discussing AI, cloud computing, and the future of software development.",
                            EndAt = new DateTime(2026, 3, 12, 18, 0, 0, 0, DateTimeKind.Utc),
                            StartAt = new DateTime(2026, 3, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Tech Workshop 2026",
                            TotalSeats = 3
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 1000,
                            Description = "One of the six World Marathon Majors, running through the heart of Berlin.",
                            EndAt = new DateTime(2026, 9, 27, 16, 0, 0, 0, DateTimeKind.Utc),
                            StartAt = new DateTime(2026, 9, 27, 8, 30, 0, 0, DateTimeKind.Utc),
                            Title = "Berlin Marathon",
                            TotalSeats = 1000
                        },
                        new
                        {
                            Id = 3,
                            AvailableSeats = 150,
                            Description = "Early-stage founders pitch their ideas to a panel of investors and industry experts.",
                            EndAt = new DateTime(2026, 4, 15, 21, 30, 0, 0, DateTimeKind.Utc),
                            StartAt = new DateTime(2026, 4, 15, 18, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Startup Pitch Night",
                            TotalSeats = 150
                        },
                        new
                        {
                            Id = 4,
                            AvailableSeats = 50,
                            EndAt = new DateTime(2026, 7, 4, 22, 0, 0, 0, DateTimeKind.Utc),
                            StartAt = new DateTime(2026, 7, 4, 17, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Jazz in the Park",
                            TotalSeats = 50
                        },
                        new
                        {
                            Id = 5,
                            AvailableSeats = 250,
                            Description = "Black-tie fundraising dinner supporting local children's hospitals.",
                            EndAt = new DateTime(2026, 11, 21, 23, 59, 0, 0, DateTimeKind.Utc),
                            StartAt = new DateTime(2026, 11, 21, 19, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Annual Charity Gala",
                            TotalSeats = 250
                        },
                        new
                        {
                            Id = 6,
                            AvailableSeats = 30,
                            Description = "Hands-on workshop covering portrait, landscape, and street photography techniques.",
                            EndAt = new DateTime(2026, 5, 8, 16, 0, 0, 0, DateTimeKind.Utc),
                            StartAt = new DateTime(2026, 5, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Photography Workshop",
                            TotalSeats = 30
                        },
                        new
                        {
                            Id = 7,
                            AvailableSeats = 5000,
                            Description = "Three-day celebration of local cuisine, international wines, and live cooking demonstrations.",
                            EndAt = new DateTime(2026, 8, 16, 20, 0, 0, 0, DateTimeKind.Utc),
                            StartAt = new DateTime(2026, 8, 14, 11, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Food & Wine Festival",
                            TotalSeats = 5000
                        },
                        new
                        {
                            Id = 8,
                            AvailableSeats = 50,
                            Description = "Deep dive into .NET 9, performance tuning, and modern C# patterns for senior developers.",
                            EndAt = new DateTime(2026, 6, 3, 17, 0, 0, 0, DateTimeKind.Utc),
                            StartAt = new DateTime(2026, 6, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "C# Advanced Workshop",
                            TotalSeats = 50
                        },
                        new
                        {
                            Id = 9,
                            AvailableSeats = 20,
                            EndAt = new DateTime(2026, 4, 22, 13, 0, 0, 0, DateTimeKind.Utc),
                            StartAt = new DateTime(2026, 4, 22, 8, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Community Clean-Up Day",
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 10,
                            AvailableSeats = 12000,
                            Description = "Over 200 publishers and authors gathering for readings, signings, and panel discussions.",
                            EndAt = new DateTime(2026, 10, 5, 19, 0, 0, 0, DateTimeKind.Utc),
                            StartAt = new DateTime(2026, 10, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Book Fair 2026",
                            TotalSeats = 12000
                        },
                        new
                        {
                            Id = 11,
                            AvailableSeats = 80,
                            Description = "Monthly UX/UI meetup featuring lightning talks and portfolio reviews.",
                            EndAt = new DateTime(2026, 6, 18, 21, 0, 0, 0, DateTimeKind.Utc),
                            StartAt = new DateTime(2026, 6, 18, 18, 30, 0, 0, DateTimeKind.Utc),
                            Title = "Product Design Meetup",
                            TotalSeats = 80
                        },
                        new
                        {
                            Id = 12,
                            AvailableSeats = 600,
                            Description = "Classic films screened outdoors at the city park. Bring your own blanket.",
                            EndAt = new DateTime(2026, 7, 25, 23, 30, 0, 0, DateTimeKind.Utc),
                            StartAt = new DateTime(2026, 7, 25, 20, 30, 0, 0, DateTimeKind.Utc),
                            Title = "Open Air Cinema Night",
                            TotalSeats = 600
                        },
                        new
                        {
                            Id = 13,
                            AvailableSeats = 250,
                            Description = "48-hour hackathon focused on building software solutions for climate and sustainability challenges.",
                            EndAt = new DateTime(2026, 9, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            StartAt = new DateTime(2026, 9, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Hackathon: Climate Tech",
                            TotalSeats = 250
                        },
                        new
                        {
                            Id = 14,
                            AvailableSeats = 5,
                            EndAt = new DateTime(2026, 5, 24, 17, 0, 0, 0, DateTimeKind.Utc),
                            StartAt = new DateTime(2026, 5, 22, 7, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Yoga & Mindfulness Retreat",
                            TotalSeats = 5
                        },
                        new
                        {
                            Id = 15,
                            AvailableSeats = 2000,
                            Description = "Live orchestral performance and countdown celebration at the city concert hall.",
                            EndAt = new DateTime(2027, 1, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            StartAt = new DateTime(2026, 12, 31, 20, 0, 0, 0, DateTimeKind.Utc),
                            Title = "New Year's Eve Concert",
                            TotalSeats = 2000
                        });
                });

            modelBuilder.Entity("EventManager.API.Models.Entities.Booking", b =>
                {
                    b.HasOne("EventManager.API.Models.Entities.Event", "Event")
                        .WithMany("Bookings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventManager.API.Models.Entities.Event", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
